import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Script src="ascii.js"></Script>
      <pre className="ascii">
        {"                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n                                                                                                                                                  \n"}
      </pre>
      <p>owned by @i.bougati</p>
    </div>
  );
}
